---
title: "COVerschmutzung"
output: html_document
date: "2023-05-02"
---

``` {r setup, include=FALSE}
# clean environment
rm(list=ls())
cat("\014")

# sets path to file
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(tidyverse)
library(ggplot2)
library(zoo)
```


```{r, data cleaning}
# load csv files
NO_df <- read.csv2("city_data/NO2.csv")

NO_hist_OL_df <- read.csv2("city_data_historic/Oldenburg_VS_181228_190328.csv")

# change col Datum to date format
NO_hist_OL_df$Datum <- as.Date(NO_hist_OL_df$Datum, format = "%d.%m.%y")

# calculates walking mean for NAs
window_size <- 48  # number of elements used for walking mean
running_mean <- rollapply(NO_hist_OL_df$ug.m, window_size, FUN = mean, na.rm = TRUE, partial = TRUE, align = "right")

# substitutes all missing values for the running mean
NO_hist_OL_df$ug.m[is.na(NO_hist_OL_df$ug.m)] <- running_mean[is.na(NO_hist_OL_df$ug.m)]

NO_OL_df <- data.frame(NO_df$Datum,NO_df$Uhrzeit,NO_df$Oldenburg_VS)

colnames(NO_OL_df) <- c("Datum", "Uhrzeit", "ug/m^3")
# change col Datum to date format
NO_OL_df$Datum <- as.Date(NO_OL_df$Datum, format = "%d.%m.%y")


# calculates walking mean for NAs
window_size <- 48  # number of elements used for walking mean
running_mean <- rollapply(NO_df$Oldenburg_VS, window_size, FUN = mean, na.rm = TRUE, partial = TRUE, align = "right")

# substitutes all missing values for the running mean
NO_OL_df$`ug/m^3`[is.na(NO_OL_df$`ug/m^3`)] <- running_mean[is.na(NO_OL_df$`ug/m^3`)]

# Create new columns with only day and month information
NO_OL_df$DayMonth <- format(NO_OL_df$Datum, "%m-%d")
NO_hist_OL_df$DayMonth <- format(NO_hist_OL_df$Datum, "%m-%d")

# Merge the DataFrames based on the common day and month
combined_NO_OL_df <- merge(NO_hist_OL_df, NO_OL_df, by.x = "DayMonth", by.y = "DayMonth")
colnames(combined_NO_OL_df) <- c("DayMonth"," Datum_hist","Uhrzeit_hist", 
                                 "ug/^3_hist","Datum_ak","Uhrzeit_ak", "ug/m^3_ak")


combined_NO_OL_filtered_df<- combined_NO_OL_df %>%
   filter(DayMonth >= "02-15" & DayMonth <= "03-15")

combined_NO_OL_filtered_df <- combined_NO_OL_filtered_df %>%
                    select(-DayMonth)

```


```{r pressure}


```

