---
title: "2. Fish Classifier"
author: "Justin König"
date: "08.05.2023"
output:
  html_document:
    keep_md: yes
    code_folding: hide
    theme: yeti
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: 72
---

``` {r setup, include=FALSE}
# clean environment
rm(list=ls())
cat("\014")

# sets path to file
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(tidyverse)
library(ggplot2)
library(zoo)
library(scales)
library(lubridate)
library(mvtnorm)
library(caret)
```


```{r, data cleaning}
# load data frame
fish_df <- read.csv2("fishcatch.csv")

# remove unnecessary data
fish_df <- fish_df[48:nrow(fish_df),]

colnames(fish_df) <- c("Species", "Length1", "Length2", "Length3","Height", "Width",
                       "sex", "Weight")

fish_df <- as.data.frame(apply(fish_df, 2, function(x) gsub(",", ".", x)))

# List the columns you want to convert to numeric
columns_to_convert <- c("Length1", "Length2", "Length3","Height", "Width",
                       "Weight")

# counts fish classes
fish_count <- fish_df %>%
  group_by(Species) %>%
  summarise(Count = n())

# Convert the specified columns to numeric
fish_df <- fish_df %>%
  mutate(across(all_of(columns_to_convert), as.numeric))


train_data <- fish_df[!(seq_len(nrow(fish_df)) %% 10 == 0), ]

# test df (every 10. Fish)
test_data <- fish_df[seq(1, nrow(fish_df), by = 10), ]
```

``` {r, visualitation}
ggplot(fish_count, aes(x = Species, y = Count)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme_classic() +
  labs(title = "Fish Count per Species",
       x = "Species",
       y = "Count")
```



``` {r, summary}

# Get the list of unique species
unique_species <- unique(fish_df$Species)

# Calculate the mean for each parameter for each species
mean_species_list <- lapply(unique_species, function(fish_species) {
  mean_species <- fish_df %>%
    filter(Species == fish_species) %>%
    summarise(Mean_Length1 = mean(Length1, na.rm = TRUE),
              Mean_Length2 = mean(Length2, na.rm = TRUE),
              Mean_Length3 = mean(Length3, na.rm = TRUE),
              Mean_Height = mean(Height, na.rm = TRUE),
              Mean_Width = mean(Width, na.rm = TRUE),
              Mean_Weight = mean(Weight, na.rm = TRUE))
  mean_species
})

# Assign names to the list elements based on species
names(mean_species_list) <- unique_species

# Print the mean values for each species
mean_species_list

```

```{r, classifieing}
# Load the data
df <- fish_df

# Split the data into training and testing sets
set.seed(42)
split_index <- sample(1:nrow(fish_df), 0.7 * nrow(fish_df))
train_data <- fish_df[split_index, ]
test_data <- fish_df[-split_index, ]

# Calculate the mean, covariance, and a-priori probability for each fish species
species_list <- unique(train_data$Species)
stats_list <- lapply(species_list, function(species) {
  species_data <- train_data[train_data$Species == species, c("Length1", "Length2", "Length3", "Height", "Width")]
  n <- nrow(species_data)
  
  list(mean = colMeans(species_data),
       cov = cov(species_data) + diag(1e-6, ncol(species_data)),
       prior = n / nrow(train_data))
})

names(stats_list) <- species_list

# Multivariate Gaussian density function
multivariate_gaussian <- function(x, mean, cov) {
  k <- length(mean)
  exp(-0.5 * t(x - mean) %*% solve(cov, x - mean)) / sqrt((2 * pi)^k * det(cov))
}

# QDA classifier
classify_fish_qda <- function(lengths) {
  likelihoods <- sapply(stats_list, function(params) {
    likelihood <- multivariate_gaussian(lengths, params$mean, params$cov)
    likelihood * params$prior
  })
  
  names(likelihoods)[which.max(likelihoods)]
}

# Classify each fish in the test set
predicted_species <- apply(test_data[, c("Length1", "Length2", "Length3", "Height", "Width")], 1, classify_fish_qda)

# Calculate the accuracy
correct_predictions <- sum(predicted_species == test_data$Species)
total_predictions <- length(predicted_species)

accuracy <- correct_predictions / total_predictions
cat("The accuracy of the QDA classifier on the test set is:", accuracy * 100, "%\n")

```
```{r, plotting }

# Create a long-format data frame
long_fish_1_df <- fish_df %>%
  dplyr::select(Species, Length1, Length2, Length3, Height, Width) %>%
  tidyr::gather(key = "Feature", value = "Value", -c(Species, Length1))

long_fish_2_df <- fish_df %>%
  dplyr::select(Species, Length1, Length2, Length3, Height, Width) %>%
  tidyr::gather(key = "Feature", value = "Value", -c(Species, Length2))

long_fish_3_df <- fish_df %>%
  dplyr::select(Species, Length1, Length2, Length3, Height, Width) %>%
  tidyr::gather(key = "Feature", value = "Value", -c(Species, Length3))

long_fish_4_df <- fish_df %>%
  dplyr::select(Species, Length1, Length2, Length3, Height, Width) %>%
  tidyr::gather(key = "Feature", value = "Value", -c(Species, Height))

long_fish_5_df <- fish_df %>%
  dplyr::select(Species, Length1, Length2, Length3, Height, Width) %>%
  tidyr::gather(key = "Feature", value = "Value", -c(Species, Width))

ggplot(long_fish_1_df, aes(x = Length1, y = Value, color = factor(Species))) +
  geom_point() +
  labs(x = "Length1", y = "Value", color = "Species") +
  theme_minimal() +
  facet_wrap(~Feature, ncol = 4) +
  ggtitle("Scatter plots of Length1 vs. other features")

ggplot(long_fish_2_df, aes(x = Length2, y = Value, color = factor(Species))) +
  geom_point() +
  labs(x = "Length2", y = "Value", color = "Species") +
  theme_minimal() +
  facet_wrap(~Feature, ncol = 4) +
  ggtitle("Scatter plots of Length2 vs. other features")

ggplot(long_fish_2_df, aes(x = Length2, y = Value, color = factor(Species))) +
  geom_point() +
  labs(x = "Length2", y = "Value", color = "Species") +
  theme_minimal() +
  facet_wrap(~Feature, ncol = 4) +
  ggtitle("Scatter plots of Length2 vs. other features")

ggplot(long_fish_3_df, aes(x = Length3, y = Value, color = factor(Species))) +
  geom_point() +
  labs(x = "Length3", y = "Value", color = "Species") +
  theme_minimal() +
  facet_wrap(~Feature, ncol = 4) +
  ggtitle("Scatter plots of Length3 vs. other features")

ggplot(long_fish_4_df, aes(x = Height, y = Value, color = factor(Species))) +
  geom_point() +
  labs(x = "Height", y = "Value", color = "Species") +
  theme_minimal() +
  facet_wrap(~Feature, ncol = 4) +
  ggtitle("Scatter plots of Height vs. other features")

ggplot(long_fish_5_df, aes(x = Width, y = Value, color = factor(Species))) +
  geom_point() +
  labs(x = "Width", y = "Value", color = "Species") +
  theme_minimal() +
  facet_wrap(~Feature, ncol = 4) +
  ggtitle("Scatter plots of Width vs. other features")
```

```{r, Boxplots}
# Create a box plot
ggplot(train_data, aes(x = Species, y = Length1, fill = Species)) +
  geom_boxplot() +
  labs(x = "Species", y = "Length1") +
  theme_minimal() +
  ggtitle("Box plot of Length1 by fish species")


# Create a box plot
ggplot(train_data, aes(x = Species, y = Length2, fill = Species)) +
  geom_boxplot() +
  labs(x = "Species", y = "Length2") +
  theme_minimal() +
  ggtitle("Box plot of Length2 by fish species")


# Create a box plot
ggplot(train_data, aes(x = Species, y = Length3, fill = Species)) +
  geom_boxplot() +
  labs(x = "Species", y = "Length3") +
  theme_minimal() +
  ggtitle("Box plot of Length3 by fish species")


# Create a box plot
ggplot(train_data, aes(x = Species, y = Height, fill = Species)) +
  geom_boxplot() +
  labs(x = "Species", y = "Height") +
  theme_minimal() +
  ggtitle("Box plot of Height by fish species")


# Create a box plot
ggplot(train_data, aes(x = Species, y = Width, fill = Species)) +
  geom_boxplot() +
  labs(x = "Species", y = "Width") +
  theme_minimal() +
  ggtitle("Box plot of Width by fish species")

```